version: '3.6'

services:
  rebuild-laravel:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        - PHP_VERSION=8.0
    image: rebuild-laravel
    hostname: rebuild-laravel
    restart: always
    ports:
      - "8088:80"
    volumes:
      - .:/var/www
      - ./docker/supervisor/supervisord.conf:/etc/supervisord.conf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    name: docker-api
    driver: bridge
