version: '3.6'

services:
  api-demo:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        - PHP_VERSION=8.0
    image: api-demo
    hostname: api-demo
    restart: always
    ports:
      - "8088:80"
    volumes:
      - .:/var/www
      - ./docker/supervisor/supervisord.conf:/etc/supervisord.conf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
      - "traefik.http.routers.api-demo.rule=Host(`${API_DEMO_HOST}`)"
    networks:
      - backend
      - gateway

#Docker Networks
networks:
  backend:
    name: docker-demo-backend
    driver: bridge
  gateway:
    name: docker-demo-gateway
    driver: bridge
