version: '3.9'

services:
  bamboo-api:
    build:
      context: .
      args:
        - PHP_VERSION=8.0
    image: bamboo-api
    hostname: bamboo-api
    restart: always
    ports:
      - "${PUBLIC_PORT}:80"
    volumes:
      - ./:/var/www
      - ./supervisor/supervisord.conf:/etc/supervisord.conf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
      - "traefik.http.routers.api-demo.rule=Host(`${API_DEMO_HOST}`)"
    networks:
      - public
      - private

#Docker Networks
networks:
  private:
    name: bamboo_private
    driver: bridge
  public:
    name: bamboo_public
    driver: bridge
